language: python
python: 3.5
sudo: required
dist: trusty
services: docker
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
      - gfortran
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - libgmp-dev
      - libglpk-dev
      - libmpfr-dev

# command to install dependencies
env:
  - PIP_CACHE_DIR=$HOME/.cache/pip
before_install:
  - rvm get head
  - (git clone https://github.com/matthew-brett/multibuild.git && cd multibuild && git checkout ffe5995)
  # matplotlib non-compatible as testing runs in venv (non-framework)
  - TEST_DEPENDS="cython codecov coverage numpy scipy python-libsbml jsonschema six pandas tabulate"
  - BUILD_DEPENDS="cython numpy scipy"
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

before_cache:
  - set +e

install:
  - python setup.py develop
# # command to run tests
script:
  - coverage run --source=cobra setup.py test
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then
    pep8 cobra --exclude=oven,solvers,sbml.py --show-source;
    fi
after_success:
  - codecov
